requires 'Mojolicious';
requires 'Perl::Critic';
requires 'PPI::HTML';
requires 'PPI::XS';

test_requires 'Test::More';
test_requires 'Carp::Always';

author_requires 'App::Ack';
author_requires 'Plack';
author_requires 'Reply';
author_requires 'Term::ReadLine';
author_requires 'Term::ReadLine::EditLine';
